### PR TITLE
Fix the size of svg logo

### PR DESCRIPTION
**Pull request by lens0021**
Though, I am not understanding the SVG at all.

### CODE REVIEW

**Comment by lens0021** [comment]
Hm, the issue I saw was maybe appears in newer Chromium?

Wavebox (114.0.5735.134):
image

Chrome (114.0.5735.106):
image

Edge (114.0.1823.51):
image

**Comment by lens0021** [comment]
@Thomas101 Hi, could you confirm whether this issue caused by Chromium?

**Comment by Thomas101** [comment]
It's probably down to the availability of fonts. The text in the SVG uses `font-family:'Futura-Medium', 'Futura', sans-serif;font-weight:500;` so if the first font isn't available it will fall back to the next which might have different character widths. I think Windows ships with Futura-Medium, but macOS and Linux don't.



macOS preview and Google Chrome & Firefox on macOS render it with cutoff text

Preview: 
Screenshot 2023-06-19 at 11 58 00

Chrome:
chrome

Firefox:
firefox

**Comment by lens0021** [comment]
Oh, then it is an issue of my environment. Thank you!

**Pull request closed without merging**
